# Generated by Django 5.2.9 on 2025-12-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
