# Generated by Django 5.2.9 on 2025-12-04 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='myshop.bikecategory')),
            ],
            options={
                'db_table': 'price_logs',
            },
        ),
    ]
